title: Aatu Alatalo Portfolio
url: "https://aatualatalo.com"
baseurl: ""

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - .gitignore
  - vendor
  - Gemfile
  - Gemfile.lock
  - "._*"
  - "**/._*"
  - ".DS_Store"